### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by hmalekdev** [myketstore/myket-developer-api-unity-sample#1]
* What went wrong:
Execution failed for task ':launcher:checkReleaseAarMetadata'.
> Could not resolve all files for configuration ':launcher:releaseRuntimeClasspath'.
   > Could not resolve com.github.myketstore:myket-billing-unity:1.1.
     Required by:
         project :launcher
      > Could not resolve com.github.myketstore:myket-billing-unity:1.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/github/myketstore/myket-billing-unity/1.1/myket-billing-unity-1.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/github/myketstore/myket-billing-unity/1.1/myket-billing-unity-1.1.pom'.
               > Read timed out

**Comment by komeilkamal** [comment]
Myket's payment library is on jitpack, not GoogleMaven.
See [here](https://github.com/myketstore/myket-developer-api-unity-sample/blob/98b9463a701ad77699a0276d4611d8337cddf021/Assets/Plugins/Android/baseProjectTemplate.gradle#L6)

**Comment by hmalekdev** [comment]
شما در فایل BaseProjectTemplate اضافه کردید که خروجی نمیده...
در اصل در فایل SettingsTemplate این خط کد باید اضافه بشه...
maven { url 'https://jitpack.io/' }
